### ISSUE TITLE
Implement InputPin from embedded_hal

### ISSUE THREAD

**Issue by arlyon** [newAM/stm32wl-hal#205]
edit: found OutputPin, seems like it's just InputPin I can't find

Hi

Apologies if this request doesn't make sense, I am still getting familiar with the ecosystem.

I am trying my hand at writing a generic driver using embedded hal, and I am using a `nucleo-wl55jc` as a test board. I would like to use the `InputPin` and `OutputPin` traits to do so but see that they aren't implemented for `Input` and `Output`. Is there a specific reason for this, or should I write a PR?

Thanks

**Comment by newAM** [comment]
I had some time after work today so I implemented this in #208, feel free to reopen the issue if that did not resolve it!
